"""The generated views (ledger/SUMMARY.md, experiments.md, learnings.md) as text: pure functions of loop data.

`scripts/loop.py` stays the only writer; its `render` reads the repo and writes what these return.
"""

from __future__ import annotations

from datetime import datetime, timedelta
from typing import NamedTuple

from loop_core import rates
from loop_core.experiments import lesson_basis, lesson_is_stale, lesson_outcome, rule_application
from loop_core.reads import best_snapshot, snapshot_cell, window_label
from loop_core.times import local, parse_time

GENERATED_HEAD = "<!-- Generated by scripts/loop.py. Do not edit; it is rewritten after every loop command. -->\n\n"


def primary_label(metric: str) -> str:
    if metric in rates.PRIMARIES:
        what = "likes plus reposts" if metric == "engagement_rate" else "profile visits"
        return f"organic {what} per 1,000 organic impressions ({metric})"
    return f"root {metric}"


def fmt_replies(snap: dict | None) -> str:
    if snap is None or snap.get("outside_replies") is None:
        return "–"
    prefix = "≥" if snap.get("repliers_complete") is False else ""
    return f"{prefix}{snap['outside_replies']}"


def fmt(value) -> str:
    return "–" if value is None else (f"{value:g}" if isinstance(value, float) else str(value))


class Shown(NamedTuple):
    """The two observations one summary row is allowed to show.

    snapshot: the 48h Snapshot, else the latest late one. Views, bookmarks, outside replies, the Snapshot column.
    activity: the 48h activity read, else the backfill. Organic, non-organic, visits. A Final read is not shown here.
    """

    snapshot: dict | None
    activity: dict | None


def shown(post: dict, row: dict | None) -> Shown:
    return Shown(best_snapshot(post), best_read(row))


def best_read(row: dict | None) -> dict | None:
    """An activity row's read for a summary cell: the 36-60h one, else the backfill. Not the Final read."""
    if not row:
        return None
    reads = row.get("reads", {})
    return reads.get("48h") or reads.get("backfill")


def nonorganic_pct(read: dict | None) -> str:
    public = (read or {}).get("public", {}).get("impressions")
    organic = (read or {}).get("organic", {}).get("impressions")
    if not public or organic is None:
        return "–"
    return f"{max(0, public - organic) * 100 // public}%"


def credited_follows(root_id: str, rows: dict[str, dict], days: list[dict]) -> int:
    total = 0
    for day in days:
        for item, count in day.get("attributed", {}).items():
            if item == root_id or rows.get(item, {}).get("conversation_id") == root_id:
                total += count
    return total


def follows_cell(root_id: str, rows: dict[str, dict], days: list[dict]) -> str:
    """X's exported follows for the post and its thread cards when known; else the credited lower bound."""
    group = [r for r in rows.values() if r["id"] == root_id or
             (r.get("conversation_id") == root_id and r.get("kind") == "thread_card")]
    exported = [r["reads"]["export"]["new_follows"] for r in group if "export" in r.get("reads", {})]
    if exported:
        return str(sum(exported))
    credited = credited_follows(root_id, rows, days)
    return f"≥{credited}" if credited else "–"


ELIGIBILITY_FOLLOWERS = 500
ELIGIBILITY_IMPRESSIONS = 500_000


def latest_organic(row: dict) -> int:
    """The highest organic impressions any read saw, including a Final read. The eligibility upper bound, not a summary cell."""
    reads = row.get("reads", {})
    seen = [(reads.get("export") or {}).get("impressions")]
    seen += [(reads.get(stage) or {}).get("organic", {}).get("impressions") for stage in ("final", "48h", "backfill")]
    return max([v for v in seen if isinstance(v, int)], default=0)


def eligibility_lines(rows: dict[str, dict], account: dict) -> list[str]:
    days, screens = account.get("days", []), account.get("eligibility", [])
    if not days and not screens:
        return []
    anchor = max([parse_time(d["at"]) for d in days] + [parse_time(s["at"]) for s in screens])
    window = [r for r in rows.values() if r["kind"] in {"original", "quote"}
              and anchor - timedelta(days=90) < parse_time(r["created_at"]) <= anchor]
    proxy = sum(latest_organic(r) for r in window)
    verified = next((d["verified_followers"] for d in reversed(days) if "verified_followers" in d), None)
    lines = ["\n## Original Content Rewards\n\n",
             f"Needs {ELIGIBILITY_FOLLOWERS} verified followers and {ELIGIBILITY_IMPRESSIONS:,} verified Home Timeline "
             "impressions on originals in 90 days (no replies, no boosted reach).\n\n"]
    if screens:
        last = screens[-1]
        lines.append(f"- X's eligibility screen, read {last['at'][:10]}: {last['verified_followers']} verified followers, "
                     f"{last['qualified_impressions']:,} qualified impressions.\n")
    if verified is not None:
        lines.append(f"- Verified followers from the daily read: {verified} of {ELIGIBILITY_FOLLOWERS}.\n")
    lines.append(f"- Organic impressions on originals and quotes, last 90 days: {proxy:,}. This counts every viewer "
                 "on every surface, so it is an upper bound; X counts only Premium viewers on the Home feed.\n")
    if screens and proxy:
        lines.append(f"- Share that qualified at the last screen reading: {screens[-1]['qualified_impressions'] * 100 // proxy}%"
                     " (the two readings may be from different days).\n")
    return lines


def account_lines(rows: dict[str, dict], days: list[dict]) -> list[str]:
    if not days:
        return []
    anchor = parse_time(days[-1]["at"])
    week = [d for d in days if parse_time(d["at"]) > anchor - timedelta(days=7)]
    new = sum(d.get("new") or 0 for d in week)
    lost = sum(d.get("lost") or 0 for d in week)
    credited = sum(sum(d.get("attributed", {}).values()) for d in week)
    recent = [r for r in rows.values() if anchor - timedelta(days=7) < parse_time(r["created_at"]) <= anchor]
    compared = [d for d in week if not d.get("baseline")]
    lines = ["\n## Account\n\n", f"Followers: {days[-1]['followers']} on {days[-1]['date']}. "]
    if not compared:
        lines.append("This is the first count; follower changes and credit start from the next day's read.\n\n")
    else:
        lines.append(f"In the 7 days to then: {new} new, {lost} lost; {credited} of the new credited to a post "
                     f"or reply they engaged with (a lower bound).\n\n")
    visits = sum((best_read(r) or {}).get("organic", {}).get("profile_visits") or 0 for r in recent)
    if visits and compared:
        lines.append(f"Follows per profile visit, items from those 7 days: {new} / {visits}.\n\n")
    lines += ["| Kind | Items | Organic impressions | Profile visits | Likes | Visits per 1,000 | New follows (X export) |\n",
              "|---|---:|---:|---:|---:|---:|---:|\n"]
    topics: dict[str, int] = {}
    for kind in ("original", "quote", "reply", "thread_card"):
        group = [r for r in recent if r["kind"] == kind]
        reads = [best_read(r)["organic"] for r in group if best_read(r)]
        if not group:
            continue
        impressions = sum(o.get("impressions") or 0 for o in reads)
        visited = sum(o.get("profile_visits") or 0 for o in reads)
        likes = sum(o.get("likes") or 0 for o in reads)
        organic = {"impressions": impressions, "profile_visits": visited}
        scored = rates.visit_rate(organic)
        rate = f"{scored:.1f}" if scored is not None and rates.above_floor(organic) else "–"
        exported = [r["reads"]["export"]["new_follows"] for r in group if "export" in r.get("reads", {})]
        follows = str(sum(exported)) if exported else "–"
        lines.append(f"| {kind.replace('_', ' ')} | {len(group)} | {impressions} | {visited} | {likes} | {rate} | {follows} |\n")
    for r in recent:
        organic = (best_read(r) or {}).get("organic", {}).get("impressions") or 0
        for topic in r.get("topics", []):
            topics[topic] = topics.get(topic, 0) + organic
    top = sorted(topics.items(), key=lambda kv: (-kv[1], kv[0]))[:5]
    if top:
        lines.append("\nTop topics by organic impressions (X's own labels, a proxy): "
                     + ", ".join(f"{name} ({count})" for name, count in top) + ".\n")
    return lines


def summary_text(posts: list[dict], rows: dict[str, dict], account: dict) -> str:
    days = account["days"]
    window = window_label()
    lines = [GENERATED_HEAD, "# Ledger summary\n\n",
             f"Times are Australia/Brisbane. Views and Snapshot come from the {window} snapshot, else the latest late one. "
             f"Organic, Non-organic and Visits come from the X API read at {window}s, else the September backfill. "
             "Follows are from X's analytics export (the post and its thread cards) when one has been recorded; "
             "≥n is the lower bound from matching new followers to who engaged. "
             "A leading ≥ means X search returned fewer reply authors than the reply count.\n\n",
             "| Posted | Slug | Format | Lane | Experiment | Views | Organic | Non-organic | Visits | Bookmarks | "
             "Outside replies | Follows | Snapshot |\n",
             "|---|---|---|---|---|---:|---:|---:|---:|---:|---:|---:|---|\n"]
    for post in posts:
        observation = shown(post, rows.get(post["root_id"]))
        snap, read = observation.snapshot, observation.activity
        root = snap["root"] if snap else {}
        organic = (read or {}).get("organic", {})
        where = snapshot_cell(post)
        exp = f"{post['experiment']} {post['arm']}" if post.get("experiment") else ("retro" if post["retrospective"] else "–")
        if post.get("nonorganic"):
            exp += ", non-organic"
        lines.append(f"| {local(post['posted_at'])} | {post['slug']} | {post['format']} | {post['lane']} | {exp} | "
                     f"{fmt(root.get('views'))} | {fmt(organic.get('impressions'))} | {nonorganic_pct(read)} | "
                     f"{fmt(organic.get('profile_visits'))} | {fmt(root.get('bookmarks'))} | "
                     f"{fmt_replies(snap)} | {follows_cell(post['root_id'], rows, days)} | {where} |\n")
    lines += eligibility_lines(rows, account)
    lines += account_lines(rows, days)
    return "".join(lines)


def experiments_text(state: dict) -> str:
    window = window_label()
    lines = [GENERATED_HEAD, "# Experiments\n\n", "One runs at a time. Rules are fixed when it opens.\n\n"]
    if not state["experiments"]:
        lines.append("None yet.\n")
    for exp in reversed(state["experiments"]):
        lines.append(f"## {exp['id']}: {exp['question']}\n\n")
        lines.append(f"- **Status:** {exp['status']}\n")
        lines.append(f"- **Treatment:** {exp['treatment']}\n")
        lines.append(f"- **Compared with:** {exp['control']}\n")
        lines.append(f"- **Primary outcome:** {primary_label(exp['primary'])} at the {window} snapshot\n")
        lines.append(f"- **Bar to beat:** {fmt(exp['threshold'])} ({exp['effect']:g} × cohort median {fmt(exp['cohort_median'])})\n")
        lines.append(f"- **Cohort, frozen {exp['opened_at'][:10]}:** "
                     + ", ".join(f"{c['root_id']} ({c['value']}, {c['kind']})" for c in exp["cohort"]) + "\n")
        for i, rnd in enumerate(exp["rounds"], start=1):
            below = [pid for pid, note in rnd.get("notes", {}).items() if note == "below_floor"]
            lines.append(f"- **Round {i}:** {rnd['passes']} of {len(rnd['posts'])} beat the bar "
                         f"({', '.join(map(str, rnd['values']))}), {rnd['result']}"
                         + (f"; below_floor, counted as a miss: {', '.join(below)}" if below else "") + "\n")
        lines.append("\n")
    return "".join(lines)


def learnings_text(state: dict, at: datetime) -> str:
    lines = [GENERATED_HEAD, "# Learnings\n\n",
             "A lesson changes the drafting rules only when its status is `adopted` and the operator types `/apply`. "
             "Fresh is whether that evidence is still inside 42 days. Rule is the latest entry in the rules list.\n\n",
             "| Lesson | Status | Fresh | Rule | Claim | Evidence | Last evidence | Basis |\n",
             "|---|---|---|---|---|---|---|---|\n"]
    rules = state.get("rules", [])
    for lesson in state["lessons"]:
        fresh = "stale" if lesson_is_stale(lesson, at) else "current"
        lines.append(f"| {lesson['id']} | {lesson_outcome(lesson)} | {fresh} | {rule_application(rules, lesson['id'])} | "
                     f"{lesson['statement']} | {', '.join(lesson['evidence'])} | {lesson['last_evidence_at'][:10]} | "
                     f"{lesson_basis(lesson, state['experiments']) or '–'} |\n")
    if not state["lessons"]:
        lines.append("| – | – | – | – | No lessons yet | – | – | – |\n")
    return "".join(lines)
